"""Mine verified 'play and win' combinations from the manual positions.

The scanned diagrams are mostly *quiet* strategic positions, not puzzles
— so instead of fabricating a solution for every position (which would
teach wrong moves), this only emits an exercise when the engine finds a
**forced win by annihilation** within a short horizon: a line that, by
the rules of the game, captures all the opponent's pieces. Such a line
is reconstructed move by move with the engine and is correct by
construction (every move is legal; the final state is a win for the
side that started).

Output: ``strategy/strategy_exercises.json`` — rows shaped like the
historical ``INITIAL_EXERCISES`` (name / initial_fen / solution_moves /
difficulty / category / hint) plus provenance back to the manual.

Run from ``backend/`` (slow — a few minutes; safe to background)::

    python -m strategy.generate_exercises
    python -m strategy.generate_exercises SIJBRANDS   # one source
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import ai_engine as ai
import game_engine as ge

from . import position_library as lib

_OUT_PATH = Path(__file__).resolve().parent / "strategy_exercises.json"

# Engine search depth for screening and line reconstruction. Combinations
# in these manuals are short (2–6 plies); depth 6 catches them while
# staying tractable over ~1300 positions.
_DEPTH = 6
# A leaf score this large means the search reached annihilation (see
# ai_engine.evaluate / game_result == ±100000). Side-to-move relative.
_WIN = 99000.0
# Hard cap on reconstructed line length (plies) — guards against any
# pathological non-terminating search.
_MAX_PLIES = 12


def _forced_win_line(state: ge.GameState) -> list[str] | None:
    """Reconstruct the forced winning line, or None if there isn't one.

    Plays the engine's best move for both sides until the original mover
    wins. Returns the PDN move list. Returns None when the position is
    not a forced win for the side to move (best score below threshold) or
    the line fails to terminate in a win within ``_MAX_PLIES``.
    """
    mover = state.turn
    ranked = ai.rank_moves(state, n=1, depth=_DEPTH)
    if not ranked or ranked[0][1] < _WIN:
        return None

    moves: list[str] = []
    cur = state
    for _ in range(_MAX_PLIES):
        best = ai.get_best_move(cur, depth=_DEPTH)
        if best is None:
            return None
        moves.append(ge.move_to_pdn(best))
        cur = ge.apply_move(cur, best)
        result = ge.game_result(cur)
        if result is not None:
            return moves if result == mover else None
    return None


def _difficulty(n_solution_plies: int) -> int:
    # Mover's own moves ≈ ceil(plies / 2). Short = easy.
    own = (n_solution_plies + 1) // 2
    if own <= 2:
        return 1
    if own <= 3:
        return 2
    return 3


def generate(sources: tuple[str, ...]) -> list[dict]:
    exercises: list[dict] = []
    positions = [
        p
        for src in sources
        for p in lib.valid_positions(src)
    ]
    total = len(positions)
    for i, p in enumerate(positions, start=1):
        if i % 100 == 0:
            print(f"  ... screened {i}/{total} ({len(exercises)} found)")
        state = ge.fen_to_board(p["fen"])
        line = _forced_win_line(state)
        if not line:
            continue
        side = "blancs" if state.turn == "white" else "noirs"
        theme = p.get("theme")
        exercises.append(
            {
                "name": f"{p['source']} — combinaison (p.{p['page']} #{p['number']})",
                "description": (
                    f"{p['source']} — diagramme {p['number']} page {p['page']}. "
                    f"Les {side} jouent et gagnent."
                ),
                "initial_fen": p["fen"],
                "solution_moves": line,
                "difficulty": _difficulty(len(line)),
                "category": "combinaisons_manuels",
                "hint": theme or "Cherchez une combinaison forcée.",
                # Provenance back to the source diagram.
                "source": p["source"],
                "page": p["page"],
                "number": p["number"],
                "diagram_id": p["id"],
                "fen_kind": p["kind"],
            }
        )
    return exercises


def main(argv: list[str]) -> int:
    sources = tuple(s.upper() for s in argv[1:]) or lib.stats().get(
        "per_source", {}
    ).keys()
    sources = tuple(sources) or ("SIJBRANDS", "SPRINGER", "ROOZENBURG", "KELLER")
    exercises = generate(tuple(sources))
    payload = {
        "$comment": (
            "Generated by strategy/generate_exercises.py — verified forced-win "
            "combinations mined from the manual diagrams. Re-runnable."
        ),
        "n_exercises": len(exercises),
        "exercises": exercises,
    }
    _OUT_PATH.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
    print(f"[ok] {len(exercises)} verified combinations → {_OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
